### ISSUE TITLE
Breaking mods like Millenaire & bed bug

### ISSUE THREAD

**Issue by DaftHunk** [InspireNXE/TimeWarp#5]
Hello, with this mod enabled I noticed that it cause the time to go backward while passing it by sleeping causing bug with mods like Millenaire
More of that when one player is going to bed and leave it, it pass the time even if nobody else is in his bed

Is it a bug already known ? 
If you want more details, feel free to ask ;)

**Comment by Grinch** [comment]
Can you elaborate a bit on your issue? The way I'm understanding it is that for whatever reason time is going backwards for you? Do you have any errors?

In regards to your second issue are you saying that sleeping is being allowed even if only one person attempts it with multiple on the server?

**Comment by DaftHunk** [comment]
Yes,
Technically it only say this in the console :  [WARNING] Time ran
backwards! Did the system time change?

Ingame it say something like : time goes from 19xxx to 15xxx, backward time
will break Millenaire beaviour

Yes indeed, technically the time pass only trigger when the player click on
"Leave Bed"

2018-07-03 16:54 GMT+02:00 Steven Downer <notifications@github.com>:

**Comment by Grinch** [comment]
I'll investigate it this evening and see if I can replicate your issues.

Can you give me an output of `/sponge version`?

**Comment by DaftHunk** [comment]
No problem 
[17:35:59] [Server thread/INFO] [nucleus]: Server ran the command: /sponge version
[17:35:59] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: SpongeForge
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-d453c3e
    SpongeForge: 1.12.2-2705-7.1.0-BETA-3206
    Minecraft Forge: 14.23.4.2705

Do you want also my plugin/mod list ?

**Comment by Grinch** [comment]
Thanks! Yes please. If you could also provide a full copy of your log I'd appreciate it.

**Comment by DaftHunk** [comment]
I was enable to send it to pastebin due to it's size :
https://www.dropbox.com/s/dfwtpgyxz7cw3a7/debug-2.log?dl=1

Modlist :
https://imgur.com/LdHxnaK

**Comment by Grinch** [comment]
Glancing at your log I do notice other issues that may be the source of some problems.

Line 28745
```
[03:50:26] [Thread-19/INFO] [FML]: SRV ERROR: Thread[Thread-19,5,SERVER]: Could not renamed saved building file to definitive name: -1656_65_585.gz
[03:50:26] [Thread-26/INFO] [FML]: SRV ERROR: Thread[Thread-26,5,SERVER]: Could not renamed saved building file to definitive name: -579_69_1080.gz
[03:50:26] [Thread-17/INFO] [FML]: SRV ERROR: Thread[Thread-17,5,SERVER]: Could not renamed saved building file to definitive name: 362_70_1438.gz
```

Line 41717
```
[05:52:01] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.api.enums.BOPPlants, values=[shortgrass, mediumgrass, bush, sprout, poisonivy, berrybush, shrub, wheatgrass, dampgrass, koru, cloverpatch, leafpile, deadleafpile, deadgrass, desertgrass, desertsprouts]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:288) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3206]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:3987) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.api.enums.BOPPlants, values=[shortgrass, mediumgrass, bush, sprout, poisonivy, berrybush, shrub, wheatgrass, dampgrass, koru, cloverpatch, leafpile, deadleafpile, deadgrass, desertgrass, desertsprouts]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201) ~[awu$a.class:?]
	at biomesoplenty.common.block.BlockBOPPlant.func_176200_f(BlockBOPPlant.java:288) ~[BlockBOPPlant.class:?]
	at net.minecraft.world.World.func_190527_a(World.java:3178) ~[amu.class:?]
	at com.pixelmonmod.pixelmon.items.ItemApricorn.func_180614_a(ItemApricorn.java:110) ~[ItemApricorn.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:3430) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1308) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zik000(NetHandlerPlayServer.java:2392) ~[pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:148) ~[PacketUtil.class:1.12.2-2705-7.1.0-BETA-3206]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) ~[hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 7 more
```

I only see one instance of it stating that time ran backwards which could be a variety of things. Note that I'm not trying to shy away from the thought that TimeWarp has an issue, just pointing out that there are other things going on in your logs as well.

I'll take a more in-depth look this evening and update you on this ticket. If you come up wtih any other information to share then please do not hesitate to do so. :)

**Comment by DaftHunk** [comment]
Thanks for taking of your time :)

Yeah I have noticed this errors but I have no clue on how to fix them
(nothing found online about them sadly)
The reason why I though about TimeWarp is simply because when I removed it,
the issues stopped

But yeah I also have filled a bug report on the mods concerned by the other
problem ;)

2018-07-03 19:56 GMT+02:00 Steven Downer <notifications@github.com>:

**Comment by Grinch** [comment]
Still investigating this, haven't forgotten about you. Not sure if I'll have enough time to really dig in to it until this weekend.

**Comment by Grinch** [comment]
Still haven't forgotten about you just haven't the time to handle it at the moment. Was there any response to the other related mods?
